-- Sample Wines for Testing
-- Run this in Supabase SQL Editor to add 3 test wines

INSERT INTO public.wines (
    name,
    slug,
    description,
    price,
    discount_type,
    discount_value,
    discount_active,
    wine_type,
    region,
    alcohol_content,
    volume,
    year,
    producer,
    in_stock,
    featured,
    image
) VALUES 
(
    'Merlot Premium 2020',
    'merlot-premium-2020',
    'Un vin roșu intens, cu arome de fructe negre și note de vanilie. Perfect pentru fripturi și preparate cu carne roșie.',
    89.99,
    'percentage',
    15,
    true,
    'red',
    'Valea Douro, Portugalia',
    13.5,
    750,
    2020,
    'Cramele Recaș',
    true,
    true,
    null
),
(
    'Chardonnay Reserve 2021',
    'chardonnay-reserve-2021',
    'Vin alb elegant cu arome de piersici, mere coapte și note de lemn. Ideal pentru pește și fructe de mare.',
    65.00,
    'fixed',
    10,
    true,
    'white',
    'Dealu Mare, România',
    12.5,
    750,
    2021,
    'Crama Jelna',
    true,
    false,
    null
),
(
    'Prosecco Superiore DOC',
    'prosecco-superiore-doc',
    'Vin spumant italian cu bule fine și persistente. Arome de pere, mere verzi și flori albe. Perfect pentru aperitiv.',
    120.00,
    'percentage',
    20,
    false,
    'sparkling',
    'Valdobbiadene, Italia',
    11.0,
    750,
    2022,
    'Villa Sandi',
    true,
    true,
    null
);
